title: kingjky's Blog
description: > # this means to ignore newlines until "baseurl:"
  안녕하세요.<br>NHN 기술신입 8기<br>루키오리TF 전경윤입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nhn.com" # the base hostname & protocol for your site, e.g. http://example.com
lang: ko


author:
  name: 'Kyung Yoon'
  last_name: 'Jeon'
#   cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  kingjky  
  email: kingjky@gmail.com
  vk_id: id201664979
#   telegram_name: vikapitoshka 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


